name: flutter_chem
description: A modern app made with Flutter, to track the chemistry's element. Including all 118 element, with their weight, radiation, consistency, type, block, and electronnegativity.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^5.4.2
  sleek_circular_slider: 1.1.0
  splashscreen: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/

    - lib/elements.json

    - lib/icons/
    - lib/widgets/
    - lib/backgrounds/
