name: elements_rework
description: A modern app to track the cemistry's elements. Including all 118 element with their weight, radiation, consistency, type, block, and electronnegativity.

publish_to: 'none'

version: 0.4.2+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.2
  splashscreen: ^1.2.0
  sleek_circular_slider: ^1.1.0
  smooth_star_rating: 1.0.4+2
  characters: ^1.0.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/

    - lib/isotopes/
    - lib/backgrounds/
    - lib/icons/